#!/usr/bin/ruby

unless system(ARGV[0]+
              ' -bundle -o .libs/libextractor_pdf.so '+
              ARGV[3..-1].join(' '))
  exit 1
end

File.open('libextractor_pdf.la','w') {
  | io |
  io.print <<EOF
# libextractor_pdf.la - a libtool library file
# Generated by ltmain.sh - GNU libtool 1.4.3 (1.922.2.110 2002/10/23 01:39:54)
#
# Please DO NOT delete this file!
# It is necessary for linking the library.

# The name that we can dlopen(3).
dlname='libextractor_pdf.so'

# Names of this library.
library_names='libextractor_pdf.so libextractor_pdf.so libextractor_pdf.so'

# The name of the static archive.
old_library=''

# Libraries that this one depends upon.
dependency_libs=''

# Version information for libextractor_rpm.
current=0
age=0
revision=0

# Is this an already installed library?
installed=no

# Files to dlopen/dlpreopen
dlopen=''
dlpreopen=''

# Directory that this library needs to be installed in:
libdir='#{ARGV[2]}'
EOF
}

File.open('.libs/libextractor_pdf.lai','w') {
  | io |
  io.print <<EOF
# libextractor_pdf.la - a libtool library file
# Generated by ltmain.sh - GNU libtool 1.4.3 (1.922.2.110 2002/10/23 01:39:54)
#
# Please DO NOT delete this file!
# It is necessary for linking the library.

# The name that we can dlopen(3).
dlname='libextractor_pdf.so'

# Names of this library.
library_names='libextractor_pdf.so libextractor_pdf.so libextractor_pdf.so'

# The name of the static archive.
old_library=''

# Libraries that this one depends upon.
dependency_libs=''

# Version information for libextractor_rpm.
current=0
age=0
revision=0

# Is this an already installed library?
installed=yes

# Files to dlopen/dlpreopen
dlopen=''
dlpreopen=''

# Directory that this library needs to be installed in:
libdir='#{ARGV[2]}'
EOF
}

