/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ovmj_libextractor_Extractor */

#ifndef _Included_org_ovmj_libextractor_Extractor
#define _Included_org_ovmj_libextractor_Extractor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ovmj_libextractor_Extractor
 * Method:    loadDefaultInternal
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_ovmj_libextractor_Extractor_loadDefaultInternal
  (JNIEnv *, jclass);

/*
 * Class:     org_ovmj_libextractor_Extractor
 * Method:    unloadInternal
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_ovmj_libextractor_Extractor_unloadInternal
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_ovmj_libextractor_Extractor
 * Method:    extractInternal
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_ovmj_libextractor_Extractor_extractInternal
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_ovmj_libextractor_Extractor
 * Method:    freeInternal
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_ovmj_libextractor_Extractor_freeInternal
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_ovmj_libextractor_Extractor
 * Method:    typeInternal
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_ovmj_libextractor_Extractor_typeInternal
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_ovmj_libextractor_Extractor
 * Method:    keywordInternal
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_ovmj_libextractor_Extractor_keywordInternal
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_ovmj_libextractor_Extractor
 * Method:    nextInternal
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_ovmj_libextractor_Extractor_nextInternal
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_ovmj_libextractor_Extractor
 * Method:    getTypeAsStringInternal
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_ovmj_libextractor_Extractor_getTypeAsStringInternal
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
