#!/usr/bin/env python
#
# test
#
# Christian Seberino
# chris@pythonsoft.com
# November 5, 2004
#
# Tests code to demo saving state between C extensions.

import bag

print "Now I will create a Bag object..."

my_bag = bag.Bag()

print "Now I will set the 3 integers of the Bag object to 2, 33 and 4..."

my_bag.set(0, 2)
my_bag.set(1, 33)
my_bag.set(2, 4)

print "Now I will print the values of the 3 integers in the Bag object..."

print my_bag.get(0), my_bag.get(1), my_bag.get(2)

print "Now I will pass the object to a function and invoke that function..."

def print_nuke_print_again(victim):
        """
        This function prints values of a Bag object, sets all values
        to zero and then prints values again.
        """
        print "BEFORE:", victim.get(0), victim.get(1), victim.get(2)
        victim.set(0, 0)
        victim.set(1, 0)
        victim.set(2, 0)
        print "AFTER: ", victim.get(0), victim.get(1), victim.get(2)

print_nuke_print_again(my_bag)
